'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter, useParams } from 'next/navigation'
import { useRequireAuth } from '@/hooks/useRequireAuth'
import { circleService, circleJoinRequestService, userService } from '@/services/api'
import { Circle, Pact } from '@/types'
import toast from 'react-hot-toast'
import { Plus, Users } from 'lucide-react'
import DetailPageHeader from '@/components/DetailPageHeader'
import { useSeedBackHistory } from '@/hooks/useSeedBackHistory'
import InviteMembersModal from '@/components/InviteMembersModal'
import ConfirmModal from '@/components/ConfirmModal'
import UserAvatarLink from '@/components/UserAvatarLink'
import PactProgressRing, { getPactProgress } from '@/components/PactProgressRing'
import LogoSpinner from '@/components/LogoSpinner'

export default function CircleDetailPage() {
  const router = useRouter(); const params = useParams(); const { user, isInitialized } = useRequireAuth(); const circleId = Number(params.id)
  const [circle, setCircle] = useState<Circle | null>(null); const [members, setMembers] = useState<any[]>([]); const [pacts, setPacts] = useState<Pact[]>([]); const [loading, setLoading] = useState(true); const [isMember, setIsMember] = useState(false); const [inviteModal, setInviteModal] = useState(false); const [leaveModal, setLeaveModal] = useState(false); const [leaving, setLeaving] = useState(false); const [memberStats, setMemberStats] = useState<any[]>([])
  useSeedBackHistory('/circles')
  useEffect(() => { if (!isInitialized) return; if (!user) { router.push('/auth/login'); return } (async () => { try { const [c, m, p] = await Promise.all([circleService.getById(circleId), circleJoinRequestService.listMembers(circleId), circleService.listPacts(circleId)]); setCircle(c.data); setMembers(m.data || []); setPacts(p.data || []); setIsMember(!!c.data?.is_member) } catch { toast.error('Failed to load circle'); router.push('/circles') } finally { setLoading(false) } })() }, [isInitialized, user, router, circleId])
  useEffect(() => { if (!members.length) { setMemberStats([]); return } Promise.allSettled(members.map(m => userService.getStats(m.user_id))).then(results => setMemberStats(results.map((r, i) => r.status === 'fulfilled' ? { ...members[i], ...(r.value.data || {}) } : null).filter(Boolean))) }, [members])
  if (!isInitialized || loading) return <div className="flex min-h-screen items-center justify-center bg-[var(--pact-bg)]"><LogoSpinner size={32} color="var(--pact-violet)" /></div>
  if (!user || !circle) return null
  const activeMembers = memberStats.filter(m => Number(m.current_streak) > 0).length; const activeStreaks = memberStats.filter(m => Number(m.current_streak) > 0).map(m => Number(m.current_streak)); const groupStreak = activeStreaks.length ? Math.min(...activeStreaks) : 0
  const handleJoin = async () => { try { await circleService.join(circleId); setIsMember(true); const m = await circleJoinRequestService.listMembers(circleId); setMembers(m.data || []); toast.success('Joined circle') } catch { toast.error('Failed to join circle') } }
  const handleLeave = async () => { setLeaving(true); try { await circleService.leave(circleId); router.push('/circles') } finally { setLeaving(false); setLeaveModal(false) } }
  return <main className="min-h-screen bg-[var(--pact-bg)] pb-24 text-[var(--pact-text)]"><DetailPageHeader title={circle.name || 'Circle'} fallbackHref="/circles" maxWidthClassName="max-w-4xl" /><div className="mx-auto max-w-4xl px-5 pb-12 pt-8">
    <header className="border-b border-[var(--pact-hairline)] pb-8"><div className="flex items-start gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full text-3xl" style={{ background: 'linear-gradient(135deg,var(--pact-pink),var(--pact-violet))' }}>{(circle as any).icon_emoji || (circle as any).emoji || circle.name?.charAt(0)}</div><div><h1 className="text-4xl font-black tracking-[-0.06em] text-[var(--pact-text)]">{circle.name}</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-[var(--pact-text-muted)]">{circle.description || 'A place to show up for each other.'}</p></div></div><p className="mt-6 text-sm text-[var(--pact-text-muted)]">Started {new Date(circle.created_at).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })} · {pacts.length} pacts made together</p><p className="mt-3 text-sm text-[var(--pact-text)]">{circle.member_count ?? members.length} people · {activeMembers} active this week · {groupStreak}d group streak</p></header>
    <section className="border-b border-[var(--pact-hairline)] py-8"><h2 className="text-xs font-bold uppercase tracking-[0.24em] text-[var(--pact-violet)]">Showing up lately</h2><div className="mt-5 flex flex-wrap gap-x-6 gap-y-4">{members.map((member: any) => { const stat = memberStats.find(s => s.user_id === member.user_id); return <div key={member.user_id} className="flex items-center gap-2"><UserAvatarLink name={member.username} avatarUrl={member.avatar_url} username={member.username} size={34} /><span className="text-sm"><span className="font-bold">{member.full_name || member.username}</span><span className="ml-2 text-[var(--pact-violet)]">{stat?.current_streak || 0}d</span></span></div> })}</div></section>
    <div className="flex flex-wrap items-center gap-5 border-b border-[var(--pact-hairline)] py-5 text-sm">{isMember && <><button onClick={() => router.push(`/pacts/create?circleId=${circleId}`)} className="flex items-center gap-2 font-bold text-[var(--pact-violet)]"><Plus className="h-4 w-4" />Create pact</button><button onClick={() => setInviteModal(true)} className="flex items-center gap-2 text-[var(--pact-text-muted)]"><Users className="h-4 w-4" />Invite members</button></>}{!isMember && <button onClick={handleJoin} className="font-bold text-[var(--pact-violet)]">Join circle</button>}<button onClick={() => setLeaveModal(true)} className="text-[var(--pact-text-faint)]">Leave</button></div>
    <section className="pt-8"><h2 className="text-xs font-bold uppercase tracking-[0.24em] text-[var(--pact-violet)]">Pacts in this circle</h2>{!isMember ? <p className="py-8 text-sm text-[var(--pact-text-muted)]">Join this circle to view its pacts.</p> : pacts.length ? <div className="mt-4">{pacts.map((pact: any) => { const progress = getPactProgress(pact); return <Link key={pact.id} href={`/pacts/${pact.id}`} className="flex items-center gap-4 border-t border-[var(--pact-hairline)] py-4 hover:border-[var(--pact-violet)]"><PactProgressRing completed={progress.completed} total={progress.total} missed={progress.missed} size={58} /><div className="min-w-0 flex-1"><p className="truncate font-bold text-[var(--pact-text)]">{pact.title}</p><p className="mt-1 text-sm text-[var(--pact-text-muted)]">Day {progress.completed} of {progress.total}</p></div></Link> })}</div> : <p className="py-8 text-sm text-[var(--pact-text-muted)]">No pacts in this circle yet.</p>}</section>
  </div>{circle && <InviteMembersModal isOpen={inviteModal} onClose={() => setInviteModal(false)} circleId={circle.id} circleName={circle.name} existingMemberIds={members.map((m: any) => m.user_id)} />}<ConfirmModal isOpen={leaveModal} onClose={() => setLeaveModal(false)} onConfirm={handleLeave} title="Leave circle?" description={`You'll lose access to ${circle.name}'s pacts until you rejoin.`} confirmLabel="Leave Circle" destructive loading={leaving} /></main>
}
